version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-keep
      - run: ./scripts/build
      - save_cache:
          paths:
            - ~/keep
            - ~/.gradle
          key: v1-keep
