version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      TERM: dumb
      PREVIOUS_FILE: /home/circleci/keep/previous.txt
      CURRENT_FILE: /home/circleci/repo/build/update-center/versions.txt
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-keep-{{ checksum "build.gradle.kts" }}
            - v1-keep
      - run: ./scripts/publish
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-keep-{{ checksum "build.gradle.kts" }}
workflows:
  version: 2
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
