#!/bin/bash
set -ef

keyfile=$(mktemp /tmp/ourkey.XXXXXX)
function finish {
  rm -f "$keyfile"
}
trap finish EXIT

echo $SIGNING_FILE | base64 --decode > $keyfile

./gradlew publish \
    -Pversion="`curl -sL https://updates.jenkins-ci.org/stable/latestCore.txt`-$CIRCLE_BUILD_NUM" \
    -Pbintray.user=$PUBLISH_USER \
    -Pbintray.apiKey=$PUBLISH_KEY \
    -Psigning.keyId=$SIGNING_KEY \
    -Psigning.password="$SIGNING_PASSWORD" \
    -Psigning.secretKeyRingFile=$keyfile \
    --stacktrace
